import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const source = JSON.parse(await readFile(resolve(root, "version.json"), "utf8"));
if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(source.version)) {
  throw new Error("version.json must contain a semantic version");
}

const packagePaths = [
  "release/npm/package-template.json",
  "packages/cli/package.json",
  "packages/contract/package.json",
  "packages/detectors/package.json",
  "packages/engine/package.json",
  "packages/model-adapter/package.json",
];
const generatedVersion = `// Generated by scripts/sync-version.mjs from version.json. Do not edit.\nexport const PRODUCT_VERSION = ${JSON.stringify(source.version)} as const;\n`;
const check = process.argv.includes("--check");
const mismatches = [];

for (const relative of packagePaths) {
  const path = resolve(root, relative);
  const pkg = JSON.parse(await readFile(path, "utf8"));
  if (pkg.version !== source.version) {
    mismatches.push(relative);
    if (!check) {
      pkg.version = source.version;
      await writeFile(path, `${JSON.stringify(pkg, null, 2)}\n`);
    }
  }
}

const generatedPath = resolve(root, "packages/contract/src/version.ts");
let current = "";
try { current = await readFile(generatedPath, "utf8"); } catch {
  // The generated file is absent before the first synchronization.
}
if (current !== generatedVersion) {
  mismatches.push("packages/contract/src/version.ts");
  if (!check) await writeFile(generatedPath, generatedVersion);
}

// Test fixtures and doc examples that pair a stored manifest with a freshly
// built issues.json must carry the current version or compatibility fails.
// A review-state example is bound to its manifest's exact bytes, so its
// digest is rewritten whenever the manifest is.
const manifestFixtures = [
  { manifest: "packages/engine/test/fixtures/review-journey/review-manifest.json" },
  { manifest: "docs/examples/minimal-review-manifest.json", state: "docs/examples/minimal-review-state.json" },
];
for (const { manifest: relative, state } of manifestFixtures) {
  const path = resolve(root, relative);
  const manifest = JSON.parse(await readFile(path, "utf8"));
  if (manifest.source_report?.tool_version !== source.version) {
    mismatches.push(relative);
    if (!check) {
      manifest.source_report.tool_version = source.version;
      await writeFile(path, `${JSON.stringify(manifest, null, 2)}\n`);
    }
  }
  if (!state) continue;
  const statePath = resolve(root, state);
  const stateDocument = JSON.parse(await readFile(statePath, "utf8"));
  const digest = createHash("sha256").update(await readFile(path)).digest("hex");
  if (stateDocument.manifest_sha256 !== digest) {
    mismatches.push(state);
    if (!check) {
      stateDocument.manifest_sha256 = digest;
      await writeFile(statePath, `${JSON.stringify(stateDocument, null, 2)}\n`);
    }
  }
}

if (check && mismatches.length > 0) {
  throw new Error(`generated version metadata is stale: ${mismatches.join(", ")}; run pnpm version:sync`);
}
